"""add check constraints homework status file_url

Revision ID: 4913f84d4683
Revises: ea7667be51a2
Create Date: 2026-03-05 22:56:39.147146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4913f84d4683'
down_revision: Union[str, None] = 'ea7667be51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('homework_submissions', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework_submissions', 'file_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('homework', 'status')
    # ### end Alembic commands ###
