"""create supervision_logs table

Revision ID: 54cbe1a76799
Revises: b4586f20001e
Create Date: 2026-03-05 22:27:13.003733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cbe1a76799'
down_revision: Union[str, None] = 'b4586f20001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('contact_method', sa.String(length=20), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('study_status', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_logs_created_at'), 'supervision_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_supervision_logs_id'), 'supervision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_logs_student_id'), 'supervision_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_supervision_logs_supervisor_id'), 'supervision_logs', ['supervisor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervision_logs_supervisor_id'), table_name='supervision_logs')
    op.drop_index(op.f('ix_supervision_logs_student_id'), table_name='supervision_logs')
    op.drop_index(op.f('ix_supervision_logs_id'), table_name='supervision_logs')
    op.drop_index(op.f('ix_supervision_logs_created_at'), table_name='supervision_logs')
    op.drop_table('supervision_logs')
    # ### end Alembic commands ###
