"""add constraints and indexes

Revision ID: ea7667be51a2
Revises: 357b3bf6c15e
Create Date: 2026-03-05 22:53:25.873449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7667be51a2'
down_revision: Union[str, None] = '357b3bf6c15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_submission_homework_student', 'homework_submissions', ['homework_id', 'student_id'])
    op.create_index('ix_supervision_student_date', 'supervision_logs', ['student_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supervision_student_date', table_name='supervision_logs')
    op.drop_constraint('uq_submission_homework_student', 'homework_submissions', type_='unique')
    # ### end Alembic commands ###
